wazuh-config-mount monta correctamente los scripts de integracion para thehive

diff --git a/wazuh/wazuh_managers/wazuh-worker-sts.yaml b/wazuh/wazuh_managers/wazuh-worker-sts.yaml
--- a/wazuh/wazuh_managers/wazuh-worker-sts.yaml
+++ b/wazuh/wazuh_managers/wazuh-worker-sts.yaml
@@ -37,11 +37,11 @@ spec:
         - name: custom-scripts #########START MY CONFIG##############
           configMap:
             name: custom-w2thive-script
+            defaultMode: 0750
         - name: custom-scripts-bash
           configMap:
             name: custom-w2thive-bash
-        - name: temp-storage      
-          emptyDir: {}            
+            defaultMode: 0750          
         - name: sentinelone-rules 
           configMap:
             name: sentinelone-rules-configmap 
@@ -73,60 +73,8 @@ spec:
             - 'sh'
             - '-c'
             - |
-              echo "Copiando scripts desde ConfigMap a directorio temporal..."
-              cp /temp-config-w2thive/custom-w2thive.py /temp-storage/ || echo "Error copiando custom-w2thive.py"
-              cp /temp-config-w2thive/custom-w2thive /temp-storage/ || echo "Error copiando custom-w2thive"
-
-              echo "Cambiando permisos y propietario en /temp-storage"
-              chmod 750 /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error cambiando permisos"
-              chown root:wazuh /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error cambiando propietario"
-
               echo "Instalando thehive4py versión en el entorno de Wazuh..."
-              /var/ossec/framework/python/bin/pip3 install thehive4py || echo "Error instalando thehive4py"
-          #    echo "Copiando archivos a /var/ossec/integrations"
-          #    cp /temp-storage/custom-w2thive.py /var/ossec/integrations/ && echo "Copiado custom-w2thive.py" || echo "Error copiando custom-w2thive.py"
-          #    cp /temp-storage/custom-w2thive /var/ossec/integrations/ && echo "Copiado custom-w2thive" || echo "Error copiando custom-w2thive" 
-
-          #    echo "Borrando los archivos originales en /temp-storage"
-          #    rm -f /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error borrando archivos"
-               
-          # echo "Verificando archivos en /temp-storage"
-          # ls -l /temp-storage/custom-w2thive.py /temp-storage/custom-w2thive || echo "Error verificando archivos en /temp-storage"              
-
-          # echo "Moviendo archivos de /temp-storage a /config-thive"
-          # mv /temp-storage/custom-w2thive.py /config-thive/custom-w2thive.py  || echo "Error moviendo custom-w2thive.py a /config-thive"
-          # mv /temp-storage/custom-w2thive /config-thive/custom-w2thive || echo "Error moviendo custom-w2thive a /config-thive"
-
-          # echo "Verificando archivos en /config-thive"
-          # ls -l /config-thive/custom-w2thive.py /config-thive/custom-w2thive || echo "Error verificando archivos en /config-thive"
-              
-          # # Asegúrate de que el directorio existe
-          # echo "Creando directorio /var/ossec/integrations si no existe..."
-          # mkdir -p /var/ossec/integrations || echo "Error creando /var/ossec/integrations"
-              
-          # echo "Verificando existencia de /var/ossec/integrations:"
-          # ls -ld /var/ossec/integrations              
-
-          # echo "Archivos en /temp-storage antes de mover:"
-          # ls -l /temp-storage/
-
-          # echo "Copiando archivos a /var/ossec/integrations"
-          # cp /temp-storage/custom-w2thive.py /var/ossec/integrations/ && echo "Copiado custom-w2thive.py" || echo "Error copiando custom-w2thive.py"
-          # cp /temp-storage/custom-w2thive /var/ossec/integrations/ && echo "Copiado custom-w2thive" || echo "Error copiando custom-w2thive"
-              
- 
-          volumeMounts:
-            - name: temp-storage
-              mountPath: /temp-storage
-              readOnly: false
-            - name: custom-scripts
-              mountPath: /temp-config-w2thive/custom-w2thive.py
-              subPath: custom-w2thive.py
-              #readOnly: true
-            - name: custom-scripts-bash
-              mountPath: /temp-config-w2thive/custom-w2thive
-              subPath: custom-w2thive
-              #readOnly: true           
+              /var/ossec/framework/python/bin/pip3 install thehive4py || echo "Error instalando thehive4py"          
       containers:
         - name: wazuh-manager
           image: 'wazuh/wazuh-manager:4.9.1'
@@ -143,15 +91,15 @@ spec:
               subPath: filebeat.yml  
             - name: temp-storage
               mountPath: /temp-storage # Aquí se monta el volumen temporal
-              readOnly: false
-            - name: custom-scripts
-              mountPath: /temp-config-w2thive/custom-w2thive.py
-              subPath: custom-w2thive.py
-              readOnly: true
+              readOnly: false   
             - name: custom-scripts-bash
-              mountPath: /temp-config-w2thive/custom-w2thive
+              mountPath: /wazuh-config-mount/integrations/custom-w2thive
               subPath: custom-w2thive
-              readOnly: true                                
+              readOnly: true
+            - name: custom-scripts
+              mountPath: /wazuh-config-mount/integrations/custom-w2thive.py
+              subPath: custom-w2thive.py
+              readOnly: true                                           
             - name: sentinelone-rules
               mountPath: /var/ossec/etc/rules/sentinelone_rules.xml
               subPath: sentinelone_rules.xml
